### ISSUE TITLE
TypeError: mouse_position_event()

### ISSUE THREAD

**Issue by lilart** [moderngl/moderngl-window#48]
> python3 water.py                    ~/coding/gpu/moderngl-window/examples/advanced(master)@LolArch
2019-11-09 18:51:51,458 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.pyglet.Window
2019-11-09 18:51:53,908 - moderngl_window.context.base.window - INFO - Context Version:
2019-11-09 18:51:53,909 - moderngl_window.context.base.window - INFO - ModernGL: 5.5.3
2019-11-09 18:51:53,915 - moderngl_window.context.base.window - INFO - vendor: Intel Open Source Technology Center
2019-11-09 18:51:53,915 - moderngl_window.context.base.window - INFO - renderer: Mesa DRI Intel(R) Sandybridge Mobile 
2019-11-09 18:51:53,915 - moderngl_window.context.base.window - INFO - version: 3.3 (Core Profile) Mesa 19.2.3
2019-11-09 18:51:53,915 - moderngl_window.context.base.window - INFO - python: 3.7.4 (default, Oct  4 2019, 06:57:26) 
[GCC 9.2.0]
2019-11-09 18:51:53,915 - moderngl_window.context.base.window - INFO - platform: linux
2019-11-09 18:51:53,915 - moderngl_window.context.base.window - INFO - code: 330
2019-11-09 18:51:53,928 - moderngl_window.loaders.program.single - INFO - Loading: programs/water/drop.glsl
2019-11-09 18:51:53,930 - moderngl_window.loaders.program.single - INFO - Loading: programs/water/wave.glsl
2019-11-09 18:51:53,930 - moderngl_window.loaders.program.single - INFO - Loading: programs/water/texture.glsl
Traceback (most recent call last):
  File "water.py", line 120, in <module>
    moderngl_window.run_window_config(Water)
  File "/home/lolart/.local/lib/python3.7/site-packages/moderngl_window/__init__.py", line 198, in run_window_config
    window.swap_buffers()
  File "/home/lolart/.local/lib/python3.7/site-packages/moderngl_window/context/pyglet/window.py", line 102, in swap_buffers
    self._window.dispatch_events()
  File "/home/lolart/.local/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 837, in dispatch_events
    self.dispatch_pending_events()
  File "/home/lolart/.local/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 874, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/home/lolart/.local/lib/python3.7/site-packages/pyglet/event.py", line 416, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler, exception)
  File "/home/lolart/.local/lib/python3.7/site-packages/pyglet/event.py", line 479, in _raise_dispatch_exception
    raise exception
  File "/home/lolart/.local/lib/python3.7/site-packages/pyglet/event.py", line 413, in dispatch_event
    if handler(*args):
  File "/home/lolart/.local/lib/python3.7/site-packages/moderngl_window/context/pyglet/window.py", line 159, in on_mouse_motion
    self._mouse_position_event_func(x, self._buffer_height - y)
TypeError: mouse_position_event() missing 2 required positional arguments: 'dx' and 'dy'

**Comment by einarf** [comment]
This is because the examples are currently using moderngl-windoe 2.0 that is currently in master.
I should probably release it soon. Either install the master branch or remove the two extra dx and dy parameters in the `mouse_position_event` method.

**Comment by einarf** [comment]
moderngl-window 2.0.0 is now on pypi, so users trying examples with the latest version on pip should not experience issues running examples.
