### ISSUE TITLE
Call ctx.line_width = 50 raise GL_INVALID_VALUE

### ISSUE THREAD

**Issue by Remering** [moderngl/moderngl-window#50]
Backend: glfw
Context OpenGL version: 450 core
Operation system: Windows 10
Python interpreter: Python 3.8.0 [MSC v.1916 64 bit (AMD64)] on win32

**I want to change `ctx.line_width` but nothing happened.**

Code:
```
from moderngl-window import *
from moderngl import *
from OpenGL.GL import *
import ctypes
import logging

class Config(WindowConfig):
    gl_version = (4, 5)
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        ctx = self.ctx
        ctx.line_width = 50
        print(ctx.error)
        print(ctx.line_width)


run_window_config(Config)
```
Log:
```
python main.py --window glfw
2019-11-16 14:15:40,698 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.glfw.Window
2019-11-16 14:15:40,995 - moderngl_window.context.base.window - INFO - Context Version:
2019-11-16 14:15:40,995 - moderngl_window.context.base.window - INFO - ModernGL: 5.5.4
2019-11-16 14:15:40,996 - moderngl_window.context.base.window - INFO - vendor: NVIDIA Corporation
2019-11-16 14:15:40,996 - moderngl_window.context.base.window - INFO - renderer: GeForce GTX 1050 Ti/PCIe/SSE2
2019-11-16 14:15:40,996 - moderngl_window.context.base.window - INFO - version: 4.5.0 NVIDIA 431.23
2019-11-16 14:15:40,996 - moderngl_window.context.base.window - INFO - python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
2019-11-16 14:15:40,996 - moderngl_window.context.base.window - INFO - platform: win32
2019-11-16 14:15:40,996 - moderngl_window.context.base.window - INFO - code: 450
GL_INVALID_VALUE
1.0
```

But according to the [document](http://docs.gl/gl4/glLineWidth), `GL_INVALID_VALUE` should be raised if param is less or equal to 0.

Use the native `glLineWidth` call has the same effect.
Code:
```
class Config(WindowConfig):
    gl_version = (4, 5)
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        try:
            glLineWidth(50)
        except GLError as error:
            print(ctypes.cast(error.description, ctypes.c_char_p).value)
            raise error

run_window_config(Config)
```
Log:
```
python main.py --window glfw
2019-11-16 14:22:41,288 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.glfw.Window
None
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - Context Version:
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - ModernGL: 5.5.4
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - vendor: NVIDIA Corporation
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - renderer: GeForce GTX 1050 Ti/PCIe/SSE2
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - version: 4.5.0 NVIDIA 431.23
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - platform: win32
2019-11-16 14:22:41,796 - moderngl_window.context.base.window - INFO - code: 450
Traceback (most recent call last):
  File "C:/WorkPlace/Python/glumpy_demo/main.py", line 151, in <module>
    run_window_config(Config, args=['--window', 'glfw'])
  File "c:\users\mafumafu\downloads\moderngl-window\moderngl_window\__init__.py", line 190, in run_window_config
    window.config = config_cls(ctx=window.ctx, wnd=window, timer=timer)
  File "C:/WorkPlace/Python/glumpy_demo/main.py", line 54, in __init__
    raise error
  File "C:/WorkPlace/Python/glumpy_demo/main.py", line 51, in __init__
    glLineWidth(50)
  File "C:\Users\mafumafu\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Users\mafumafu\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenGL\error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'\xce\xde\xd0\xa7\xd6\xb5',
	baseOperation = glLineWidth,
	cArguments = (50,)
)
```

But everything goes well if I create a standalone context.
```
λ python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from moderngl import *
>>> ctx = create_standalone_context()
>>> from OpenGL.GL import *
>>> glLineWidth(50)
>>> glGetFloat(GL_LINE_WIDTH)
50.0
>>> ctx.line_width
50.0
```
What should I do to solve it?

PS:
`ctx.point_size` goes well.
Code:
```
class Config(WindowConfig):
    gl_version = (4, 5)
    window_size = (640, 360)
    aspect_ratio = 16 / 9
    log_level = logging.DEBUG

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        ctx = self.ctx
        glPolygonMode(GL_FRONT_AND_BACK, GL_POINT)
        print(ctx.error)
        print(ctx.point_size)
        # Useless details


run_window_config(Config)
```
Log:
```
python main.py --window glfw
2019-11-16 14:33:45,808 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.glfw.Window
2019-11-16 14:33:46,303 - moderngl_window.context.base.window - INFO - Context Version:
2019-11-16 14:33:46,303 - moderngl_window.context.base.window - INFO - ModernGL: 5.5.4
2019-11-16 14:33:46,305 - moderngl_window.context.base.window - INFO - vendor: NVIDIA Corporation
2019-11-16 14:33:46,305 - moderngl_window.context.base.window - INFO - renderer: GeForce GTX 1050 Ti/PCIe/SSE2
2019-11-16 14:33:46,305 - moderngl_window.context.base.window - INFO - version: 4.5.0 NVIDIA 431.23
2019-11-16 14:33:46,305 - moderngl_window.context.base.window - INFO - python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
2019-11-16 14:33:46,305 - moderngl_window.context.base.window - INFO - platform: win32
2019-11-16 14:33:46,305 - moderngl_window.context.base.window - INFO - code: 450
GL_NO_ERROR
50.0
```
Image:
![image](https://user-images.githubusercontent.com/26853503/68989250-9bbd5700-087e-11ea-9726-df7e962892a4.png)

**Comment by einarf** [comment]
Line with needs to be inside the opengl implementation's specified range and is only guaranteed to be 1.0 at most.

You can query the range with PyOpenGL:
```
print(glGetDoublev(GL_LINE_WIDTH_RANGE))
```

**Comment by Remering** [comment]
> Line with needs to be inside the opengl implementation's specified range and is only guaranteed to be 1.0 at most.
> 
> You can query the range with PyOpenGL:
> 
> ```
> print(glGetDoublev(GL_LINE_WIDTH_RANGE))
> ```

I got `[1., 1.]` so it's impossible to change the line width?

**Comment by Remering** [comment]
```
>>> from OpenGL.GL import *
>>> from moderngl import *
>>> ctx = create_standalone_context()
>>> glGetDoublev(GL_LINE_WIDTH_RANGE)
array([ 0.5, 10. ])
>>> ctx.line_width = 50
>>> ctx.error
'GL_NO_ERROR'
```

**Comment by einarf** [comment]
I think the driver you get when requesting headless context on nvidia is different compared to a visible window.

We don't do anything special in the moderngl `line_width` property.
https://github.com/moderngl/moderngl/blob/732dd21b675a6d1d5e5fea682122f34c00f8e87a/moderngl/old/Context.cpp#L495-L505

Generally in modern opengl you use geometry shaders to draw thick lines.

**Comment by Remering** [comment]
Causes of this issue are complex, creating context via native C++ `glfw` call and Python `glfw` got different `GL_LINE_WIDTH_RANGE`: `[1., 10.]` on C++ and `[1., 1.]` on Python, maybe I should change my minds.

**Comment by einarf** [comment]
It may be to different contect parameters. You could play around with them:
https://github.com/moderngl/moderngl-window/blob/a4d50d7060c8b3cf64f9acf578a50aed181b2c04/moderngl_window/context/glfw/window.py#L29-L38

But again, there are no guarantee of support for line with greater than 1.0, so if you rely on it supporting up to 10 it may only work on some computers.

**Comment by Remering** [comment]
After configuration with same window hints, C++ native calls have the behavior, maybe I should review `glfw` .

**Comment by einarf** [comment]
There is nothing wrong with glfw. Just don't rely on line width working and find other ways to render thick lines. Especially if you are rendering with the programmable pipleine (3.3+).
