### ISSUE TITLE
Does moderngl-window supports loading sampler1D?

### ISSUE THREAD

**Issue by aegroto** [moderngl/moderngl-window#71]
I'm trying to pass to a GLSL shader some data contained in a numpy's ndarray. I've tried to pass it to my shader on each frame like this:

```
self.prog['frequency_bins'].value = frequency_bins
self.prog['current_frequencies'].value = current_frequencies
```

In the fragment shader I declare the variables:

```
uniform sampler1D frequency_bins;
uniform sampler1D current_frequencies;
```

But I get this error:

```
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    main()
  File "main.py", line 177, in main
    mglw.run_window_config(VideoWindow)
  File "/home/lorenzo/.local/lib/python3.6/site-packages/moderngl_window/__init__.py", line 198, in run_window_config
    window.render(current_time, delta)
  File "/home/lorenzo/.local/lib/python3.6/site-packages/moderngl_window/context/base/window.py", line 599, in render
    self.render_func(time, frame_time)
  File "main.py", line 165, in render
    self.prog['frequency_bins'].value = frequency_bins
  File "/home/lorenzo/.local/lib/python3.6/site-packages/moderngl/program_members/uniform.py", line 164, in value
    self.mglo.value = value
moderngl.error.Error: cannot detect uniform type
```

I've not faced any problem using sampler2D, but for that type I can use the load_texture_2d(...) function, loading them from the disk. Is there a way to pass arrays directly from python to shaders? I may bake those data into textures and load them from files but I find this cumbersome. I'm sure there's a way, maybe using the direct moderngl context. 

I don't know how much useful it can be, but here's the full project: https://gitlab.com/aegroto/py-glsl-audiovisualizer. It should run without any issues, still the test files I use are not included for size reasons. I may upload those later on though.

**Comment by einarf** [comment]
You cannot write data directly to sampler uniforms like that. Samplers actually read from the texture channel assigned to them, so data needs to be written to a texture.

We don't actually have 1D texture support in moderngl simply because you can make an `(n, 1)` 2d texture achieving pretty much the same. I still think the sampler needs to be `sampler2D` were you leave the `y/v` coordinate as 0.

If you have data in an np array you an just create a texture manually.
```
# Using 1 component with default a bit data. You might need to specify another dtype
tex1 = ctx.texture(size, data1, 1)
tex1 = ctx.texture(size, data2, 1)

# Assign texture channels to samplers
program['frequency_bins'].value = 0
program['current_frequencies'].value = 1

# Bind textures to the channels 
tex1.use(location=0)
tex2.use(location=1)
```

```glsl
uniform sampler2D frequency_bins;
uniform sampler2D current_frequencies;
````

**Comment by einarf** [comment]
Yup. `sampler2D` works just fine. We've discussed adding the opengl 1D type, but techincally it's not really needed and we've planning to merge all texture types into one type in the future anyway.

When people have trouble with something we try sometimes to make what they are trying do into a public example. Activities like this happens on discord.
